export const GET_ALL_FOODS = 'GET_ALL_FOODS';
export const SET_FOOD_RESULT='SET_FOOD_RESULT';
export const FETCH_RESULT_FAILED='FETCH_RESULT_FAILED';
export const ADD_FOOD_ITEM="ADD_FOOD_ITEM";
export const START_TRACKING="START_TRACKING";
export const GET_ALL_FOODS_INIT="GET_ALL_FOODS_INIIT";

export const CHANGE_DIRECT_URL="CHANGE_DIRECT_URL";
export const AUTH_START="AUTH_START";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAILURE="AUTH_FAILURE";
export const AUTH_LOGOUT="AUTH_LOGOUT";
export const CHECK_STATUS="CHECK_STATUS";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
export const SINGUP_FAILURE="SIGNUP_FAILURE";