
INSERT INTO FOOD (ID,NAME,GRAMS_CALORIE,CUP_CALORIE,PIECE_CALORIE) VALUES(1,'Roti',297,64,48);
INSERT INTO FOOD (ID,NAME,GRAMS_CALORIE,CUP_CALORIE,PIECE_CALORIE) VALUES(2,'Rice',297,64,48);
INSERT INTO FOOD (ID,NAME,GRAMS_CALORIE,CUP_CALORIE,PIECE_CALORIE) VALUES(3,'Bread',297,64,48);
INSERT INTO FOOD (ID,NAME,GRAMS_CALORIE,CUP_CALORIE,PIECE_CALORIE) VALUES(4,'Oats',297,64,48);
INSERT INTO FOOD (ID,NAME,GRAMS_CALORIE,CUP_CALORIE,PIECE_CALORIE) VALUES(5,'Brown Rice',297,64,48);
INSERT INTO FOOD (ID,NAME,GRAMS_CALORIE,CUP_CALORIE,PIECE_CALORIE) VALUES(6,'Eggs',297,64,48);
INSERT INTO FOOD (ID,NAME,GRAMS_CALORIE,CUP_CALORIE,PIECE_CALORIE) VALUES(7,'Banana',297,64,48);
INSERT INTO FOOD (ID,NAME,GRAMS_CALORIE,CUP_CALORIE,PIECE_CALORIE) VALUES(8,'Apple',297,64,48);
INSERT INTO FOOD (ID,NAME,GRAMS_CALORIE,CUP_CALORIE,PIECE_CALORIE) VALUES(9,'Chicken',297,64,48);